
exclude: [..., "ReadMe.md"]

highlighter: rouge
# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Joelle Mbatchou - Webpage
author :
  name : Joelle Mbatchou
  email : jmbatchou@uchicago.edu
  github : joellesophya
  twitter : jojoladisco
  feedburner : nil
  
  
markdown: kramdown

# Have Jekyll automatically get my time zone
timezone: TIMEZONE

# Tell Jekyll to show future posts
future: true

# production_url : http://joellesophya.github.io

google_analytics: UA-96673765-1
